### ISSUE TITLE
Loop with internal variable

### ISSUE THREAD

**Issue by bencz** [LADSoft/Simple-MSIL-Compiler#1]
I used all my day trying to fix the code generation for this case:
```
int main()
{
	int i = 0;
	int valor = 0;
	int sucess = 1;
	while (sucess)
	{
		valor = i * 10;
		printf("%d\n", valor);
		if(i >= 200)
			sucess = 0;
		i++;
	}
	return 0;
}
```
The generated code it is a bit wrong, let's look for the generated code:
```
.method public hidebysig static int32 'main'() cil managed
{
	.locals
	(
		[0] int32 'i/0',
		[1] int32 'valor/1',
		[2] int32 'sucess/2'
	)
	.maxstack	3
L_2:
	ldc.i4	0
	conv.i4
	ldc.i4	0
	stloc	'i/0'
	ldc.i4	0
	stloc	'valor/1'
	ldc.i4	1
	stloc	'sucess/2'
	br	'L_7'
L_5:
	ldloc	'i/0'
	ldc.i4	10
  	mul

	ldsflda	valuetype 'int8[]' 'L_1'

	call	vararg void 'printf'(void*, ..., int32)
	ldloc	'i/0'
	ldc.i4	2000
	blt	'L_9'
	ldc.i4	0
	stloc	'sucess/2'
L_9:
	ldloc	'i/0'
	ldc.i4	10
	add
	ldc.i4	1
	add
	stloc	'i/0'
L_7:
	ldloc	'sucess/2'
	ldc.i4	0
	bne.un	'L_5'
L_6:
	ldc.i4	0
	br	'L_3'
L_3:
	ret
}
```

Let's look for the correction...
When the system do the multiplication "valor = i * 10", the generate code is:
```
  	ldloc	'i/0'
  	ldc.i4	10
  	mul
```
But it should be:
```
  	ldloc	'i/0'
  	ldc.i4	10
  	mul
  	stloc 'valor/1'
```
In printf, the the compiler not put the 'valor/1' in the stack:
```
  	ldsflda	valuetype 'int8[]' 'L_1'
  	call	vararg void 'printf'(void*, ..., int32)
```
It should be:
```
  	ldsflda	valuetype 'int8[]' 'L_1'
  	ldloc 'valor/1'
  	call	vararg void 'printf'(void*, ..., int32)
```

And, in the if, the compiler generate the wrong number... Instead of 200 it generates 2000
The compiler generated a new variable ( look at the first line from the method... )
```
	ldc.i4	0
	conv.i4
```

**Comment by bencz** [comment]
Ok, I got the problem... it's a optimization problem..., I disabled the optimization and the compiler generated the correctly code...

**Comment by LADSoft** [comment]
Hi Alexandre,

Thank you for making those tests apps available!   That was a good idea :)

I'm happy with the progress so I advertised a little on my web site and 
in the forum.

David


Alexandre Bencz wrote:
